"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	async up(queryInterface, Sequelize) {
		await queryInterface.bulkInsert(
			"facilities",
			[
				{
					facility_id: 100,
					facility_name: "Facility A",
				},
				{
					facility_id: 101,
					facility_name: "Facility B",
				},
				{
					facility_id: 102,
					facility_name: "Facility C",
				},
			],
			{}
		);

		await queryInterface.bulkInsert(
			"jobs",
			[
				{
					job_id: 210,
					facility_id: 102,
					nurse_type_needed: "LPN",
					total_number_nurses_needed: 3,
				},
				{
					job_id: 209,
					facility_id: 102,
					nurse_type_needed: "CNA",
					total_number_nurses_needed: 4,
				},
				{
					job_id: 208,
					facility_id: 100,
					nurse_type_needed: "RN",
					total_number_nurses_needed: 1,
				},
				{
					job_id: 207,
					facility_id: 101,
					nurse_type_needed: "CNA",
					total_number_nurses_needed: 1,
				},
				{
					job_id: 206,
					facility_id: 101,
					nurse_type_needed: "LPN",
					total_number_nurses_needed: 2,
				},
				{
					job_id: 205,
					facility_id: 100,
					nurse_type_needed: "RN",
					total_number_nurses_needed: 3,
				},
				{
					job_id: 204,
					facility_id: 102,
					nurse_type_needed: "RN",
					total_number_nurses_needed: 2,
				},
				{
					job_id: 203,
					facility_id: 102,
					nurse_type_needed: "LPN",
					total_number_nurses_needed: 2,
				},
				{
					job_id: 202,
					facility_id: 100,
					nurse_type_needed: "CNA",
					total_number_nurses_needed: 2,
				},
				{
					job_id: 201,
					facility_id: 101,
					nurse_type_needed: "LPN",
					total_number_nurses_needed: 1,
				},
				{
					job_id: 200,
					facility_id: 100,
					nurse_type_needed: "RN",
					total_number_nurses_needed: 1,
				},
			],
			{}
		);

		await queryInterface.bulkInsert(
			"nurses",
			[
				{
					nurse_id: 1010,
					nurse_name: "Mark",
					nurse_type: "LPN",
				},
				{
					nurse_id: 1009,
					nurse_name: "Robert",
					nurse_type: "LPN",
				},
				{
					nurse_id: 1008,
					nurse_name: "Cory",
					nurse_type: "RN",
				},
				{
					nurse_id: 1007,
					nurse_name: "Adam",
					nurse_type: "CNA",
				},
				{
					nurse_id: 1006,
					nurse_name: "Wesley",
					nurse_type: "RN",
				},
				{
					nurse_id: 1005,
					nurse_name: "Sam",
					nurse_type: "CNA",
				},
				{
					nurse_id: 1004,
					nurse_name: "Thomas",
					nurse_type: "LPN",
				},
				{
					nurse_id: 1003,
					nurse_name: "John",
					nurse_type: "LPN",
				},
				{
					nurse_id: 1002,
					nurse_name: "Abby",
					nurse_type: "RN",
				},
				{
					nurse_id: 1001,
					nurse_name: "Anne",
					nurse_type: "CNA",
				},
				{
					nurse_id: 1000,
					nurse_name: "Kevin",
					nurse_type: "CNA",
				},
			],
			{}
		);

		await queryInterface.bulkInsert(
			"nurse_hired_jobs",
			[
				{
					job_id: 210,
					nurse_id: 1004,
				},
				{
					job_id: 209,
					nurse_id: 1001,
				},
				{
					job_id: 208,
					nurse_id: 1006,
				},
				{
					job_id: 207,
					nurse_id: 1005,
				},
				{
					job_id: 206,
					nurse_id: 1010,
				},
				{
					job_id: 206,
					nurse_id: 1003,
				},
				{
					job_id: 205,
					nurse_id: 1008,
				},
				{
					job_id: 204,
					nurse_id: 1008,
				},
				{
					job_id: 204,
					nurse_id: 1006,
				},
				{
					job_id: 203,
					nurse_id: 1004,
				},
				{
					job_id: 202,
					nurse_id: 1007,
				},
				{
					job_id: 201,
					nurse_id: 1003,
				},
				{
					job_id: 200,
					nurse_id: 1006,
				},
			],
			{}
		);

		await queryInterface.bulkInsert(
			"clinician_work_histories",
			[
				{
					work_history_id: 73,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 72,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 71,
					facility_id: 100,
					nurse_id: 5,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 70,
					facility_id: 100,
					nurse_id: 5,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 69,
					facility_id: 100,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 68,
					facility_id: 100,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 67,
					facility_id: 100,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 66,
					facility_id: 100,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 65,
					facility_id: 100,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 64,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 63,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 62,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 61,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 60,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 59,
					facility_id: 100,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 58,
					facility_id: 100,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 57,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 56,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 55,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 54,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 53,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 52,
					facility_id: 102,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 51,
					facility_id: 102,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 50,
					facility_id: 102,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 49,
					facility_id: 102,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 48,
					facility_id: 102,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 47,
					facility_id: 102,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 46,
					facility_id: 102,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 45,
					facility_id: 102,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 44,
					facility_id: 102,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 43,
					facility_id: 102,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 42,
					facility_id: 102,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 41,
					facility_id: 102,
					nurse_id: 1,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 40,
					facility_id: 102,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 39,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 38,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 37,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 36,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 35,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 34,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 33,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 32,
					facility_id: 101,
					nurse_id: 4,
					worked_shift: false,
					call_out: false,
					no_call_no_show: true,
				},
				{
					work_history_id: 31,
					facility_id: 101,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 30,
					facility_id: 101,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 29,
					facility_id: 101,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 28,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 27,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 26,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 25,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 24,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 23,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 22,
					facility_id: 101,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 21,
					facility_id: 101,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 20,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 19,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 18,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 17,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 16,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 15,
					facility_id: 100,
					nurse_id: 5,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 14,
					facility_id: 100,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 13,
					facility_id: 100,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 12,
					facility_id: 100,
					nurse_id: 2,
					worked_shift: false,
					call_out: false,
					no_call_no_show: true,
				},
				{
					work_history_id: 11,
					facility_id: 100,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 10,
					facility_id: 102,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 9,
					facility_id: 102,
					nurse_id: 4,
					worked_shift: false,
					call_out: true,
					no_call_no_show: false,
				},
				{
					work_history_id: 8,
					facility_id: 102,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 7,
					facility_id: 102,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 6,
					facility_id: 102,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 5,
					facility_id: 101,
					nurse_id: 5,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 4,
					facility_id: 101,
					nurse_id: 4,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 3,
					facility_id: 101,
					nurse_id: 3,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 2,
					facility_id: 101,
					nurse_id: 2,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
				{
					work_history_id: 1,
					facility_id: 101,
					nurse_id: 1,
					worked_shift: true,
					call_out: false,
					no_call_no_show: false,
				},
			],
			{}
		);
	},

	async down(queryInterface, Sequelize) {
		/**
		 * Add commands to revert seed here.
		 *
		 * Example:
		 * await queryInterface.bulkDelete('People', null, {});
		 */
	},
};
